name: 通过 GitHub Pages 部署网站

on:
  push:
    branches: ["main"]
    paths-ignore:
    - 'README.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 验证仓库
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 上传页面
        uses: actions/upload-pages-artifact@v1
        with:
          path: "."

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署页面
        id: deployment
        uses: actions/deploy-pages@v1
